server:
  port: 8081

security:
  oauth2:
    client:
      client-id: janle1
      client-secret: janleSecret
      user-authorization-uri: http://www.clouds1000.com/oauth/authorize
      access-token-uri: http://www.clouds1000.com/oauth/token
    resource:
      jwt:
        #需要携带client
        key-uri: http://www.clouds1000.com/oauth/token_key
passport:
  security:
    oauth2:
      tokenStore: jwt

logging:
  level:
    root: debug

