server:
  port: 8080



logging:
  level:
    root: info

security:
  oauth2:
    client:
      client-id: janle
      client-secret: janleSecret
      user-authorization-uri: http://www.clouds1000.com/oauth/authorize
      access-token-uri: http://www.clouds1000.com/oauth/token
      scope: all
      registered-redirect-uri: http://client.clouds1000.com:8080/passport
    resource:
      token-info-uri: http://www.clouds1000.com/oauth/check_token
      user-info-uri: http://www.clouds1000.com/user
      jwt:
        #需要携带client
        key-uri: http://www.clouds1000.com/oauth/token_key
        key-value: janle
