server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-l9zvjuql.sql.tencentcdb.com:62750/user_center?useUnicode=true
    username: root
    password: Rfvnji_0890
  redis:
    password: redisDbs
    database: 6
    port: 6379
    host: 140.143.122.180
  #设置分布式会话
  session:
    store-type: redis


# 登录配置页面
passport:
  security:
    browser:
      login-type: JSON
    code:
      image:
        #配置需要验证码的url
        url: /login/form
        length: 4
    oauth2:
      jwtSigningKey: janle

logging:
  level:
    root: info

