server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-l9zvjuql.sql.tencentcdb.com:62750/user_center?useUnicode=true
    username: root
    password: Rfvnji_0890

  #设置分布式会话
  session:
    store-type: none



# 登录配置页面
passport:
  security:
    browser:
      login-page: /login.html
      login-type: REDIRECT
    code:
      image:
        #配置需要验证码的url
        url: /login/form
        length: 4
    social:
      qq:
        appId:

