server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-l9zvjuql.sql.tencentcdb.com:62750/user_center?useUnicode=true
    username: root
    password: Rfvnji_0890

  #设置分布式会话
  session:
    store-type: none



# 登录配置页面
passport:
  security:
    browser:
      login-page: /login.html
      sign-up-page: /singn.html
      login-type: REDIRECT
    code:
      image:
        #配置需要验证码的url
        url: /login/form
        length: 4
    social:
      filterProcessesUrl: /auth
      qq:
        appId: 101570353
        appSecret: 38df55b81ab8a77733d876108a462c18
        providerId: qq
      weixin:
        appId: wx23aa2d7d2d048069
        appSecret: 48e40d14b75be8bf7974b01833fd05d1
        providerId: weixin

logging:
  level:
    root: info

