server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-l9zvjuql.sql.tencentcdb.com:62750/user_center?useUnicode=true
    username: root
    password: Rfvnji_0890
  redis:
    password: redisDbs
    database: 6
    port: 6379
    host: 140.143.122.180
  #设置分布式会话
  session:
    store-type: REDIS
    #单位是s，tomcat的session会转化为分，最小为1分钟，具体看 org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.configureSession
    timeout: 10000



# 登录配置页面
passport:
  security:
    browser:
      login-page: /login.html
      sign-up-page: /singn.html
      login-type: REDIRECT
    code:
      image:
        #配置需要验证码的url
        url: /login/form
        length: 4
    social:
      filterProcessesUrl: /auth
      qq:
        appId: 101570353
        appSecret: 38df55b81ab8a77733d876108a462c18
        providerId: qq
      weixin:
        appId: wxab5dea732af2e72f
        appSecret: b961d044fb0030bc24031c119f652202
        providerId: weixin

logging:
  level:
    root: info

