server:
  port: 8080

security:
  oauth2:
    client:
      client-id: janle
      client-secret: janleSecret
      user-authorization-uri: http://www.clouds1000.com/oauth/authorize
      access-token-uri: http://www.clouds1000.com/oauth/token
      scope: all
    resource:
      jwt:
        #需要携带client
        key-uri: http://www.clouds1000.com/oauth/token_key
        key-value: janle

logging:
  level:
    root: info

