server:
  port: 8081



logging:
  level:
    root: debug

security:
  oauth2:
    client:
      client-id: janle1
      client-secret: janleSecret
      user-authorization-uri: http://www.clouds1000.com/oauth/authorize
      access-token-uri: http://www.clouds1000.com/oauth/token
      scope: all
    resource:
      token-info-uri: http://www.clouds1000.com/oauth/check_token
      user-info-uri: http://www.clouds1000.com/user
      jwt:
        #需要携带client
        key-uri: http://www.clouds1000.com/oauth/token_key
        key-value: janle
